# Generated by Django 4.2.28 on 2026-02-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteS1',
            fields=[
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('ncc_dpr110', models.FloatField(default=0)),
                ('nsn_dpr110', models.FloatField(default=0)),
                ('nsr_dpr110', models.FloatField(blank=True, null=True)),
                ('moy_dpr110', models.FloatField(default=0)),
                ('capit_dpr110', models.CharField(max_length=10)),
                ('moy_general', models.FloatField()),
                ('credit_total', models.IntegerField()),
                ('decision', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'notes_s1',
            },
        ),
    ]
